import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { createWoodMaterial } from "../../../materials/createWoodMaterial";
import { createStoneMaterial } from "../../../materials/createStoneMaterial";
import { createMetalMaterial } from "../../../materials/createMetalMaterial";
import { useWorldStore } from "../../../store/worldStore";
const woodDark = createWoodMaterial({ woodColor: "#3a2416", roughness: 0.9 });
const woodMid = createWoodMaterial({ woodColor: "#5c3c24", roughness: 0.85 });
const woodLight = createWoodMaterial({ woodColor: "#8c6239", roughness: 0.8 });
const stoneFloor = createStoneMaterial({ stoneColor: "#403e3b", roughness: 0.95 });
const iron = createMetalMaterial({ kind: "iron" });
export function TavernInterior({ w, d, storyH }) {
    const isNight = useWorldStore((s) => s.timeOfDay >= 18 || s.timeOfDay <= 6);
    const lightIntensity = isNight ? 1.5 : 0.5;
    return (_jsxs("group", { children: [_jsx("mesh", { position: [0, 0.05, 0], receiveShadow: true, material: woodDark, children: _jsx("boxGeometry", { args: [w - 0.2, 0.1, d - 0.2] }) }), _jsxs("group", { position: [-w / 4, 0.6, -d / 4], children: [_jsx("mesh", { castShadow: true, receiveShadow: true, material: woodMid, children: _jsx("boxGeometry", { args: [w / 2 - 1, 1.1, 0.8] }) }), _jsx("mesh", { position: [0, 0.6, 0], castShadow: true, receiveShadow: true, material: woodLight, children: _jsx("boxGeometry", { args: [w / 2 - 0.8, 0.1, 1.0] }) })] }), [{ x: w / 4, z: d / 4 }, { x: w / 4, z: -d / 4 }, { x: -w / 4, z: d / 4 }].map((pos, i) => (_jsxs("group", { position: [pos.x, 0.45, pos.z], children: [_jsx("mesh", { castShadow: true, receiveShadow: true, material: woodMid, children: _jsx("cylinderGeometry", { args: [0.6, 0.6, 0.1, 12] }) }), _jsx("mesh", { position: [0, -0.2, 0], castShadow: true, receiveShadow: true, material: woodDark, children: _jsx("cylinderGeometry", { args: [0.1, 0.1, 0.4, 8] }) }), _jsx("mesh", { position: [0, 0.1, 0], material: iron, children: _jsx("cylinderGeometry", { args: [0.05, 0.05, 0.1, 6] }) }), _jsx("pointLight", { position: [0, 0.3, 0], intensity: lightIntensity * 0.5, distance: 3, color: "#ffb366" })] }, i))), _jsxs("group", { position: [0, 1.2, -d / 2 + 0.4], children: [_jsx("mesh", { castShadow: true, receiveShadow: true, material: stoneFloor, children: _jsx("boxGeometry", { args: [2.5, 2.4, 0.8] }) }), _jsx("mesh", { position: [0, -0.6, 0.3], material: iron, children: _jsx("boxGeometry", { args: [1.5, 1.0, 0.6] }) }), _jsx("pointLight", { position: [0, -0.5, 0.6], intensity: lightIntensity * 2, distance: 8, color: "#ff6600" })] }), _jsx("group", { position: [w / 2 - 0.8, 1, 0], children: Array.from({ length: 8 }).map((_, i) => (_jsx("mesh", { position: [0, i * 0.25 - 0.8, i * 0.25 - 0.8], castShadow: true, receiveShadow: true, material: woodMid, children: _jsx("boxGeometry", { args: [1.2, 0.1, 0.3] }) }, `stair-${i}`))) }), _jsx("pointLight", { position: [0, storyH - 0.5, 0], intensity: lightIntensity, distance: 10, color: "#ffd480" })] }));
}
//# sourceMappingURL=TavernInterior.js.map